import { Link } from 'react-router-dom'
import { Activity, FileText, MessageSquare } from 'lucide-react'

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'

export function HomePage() {
  return (
    <div className="container mx-auto flex flex-col gap-12 px-6 py-16">
      <header className="flex flex-col items-center gap-4 text-center">
        <span className="inline-flex items-center rounded-full border bg-muted px-3 py-1 text-xs font-medium text-muted-foreground">
          RAG over your own documents
        </span>
        <h1 className="text-balance text-4xl font-semibold tracking-tight sm:text-5xl">
          Lumindex
        </h1>
        <p className="max-w-2xl text-balance text-muted-foreground">
          Upload your documents, ask questions in natural language, get answers grounded in your
          own content with clickable source citations.
        </p>
        <div className="flex flex-wrap items-center justify-center gap-3">
          <Link
            to="/documents"
            className="inline-flex h-9 items-center justify-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:bg-primary/90"
          >
            Get started
          </Link>
          <a
            href="https://github.com"
            target="_blank"
            rel="noreferrer"
            className="inline-flex h-9 items-center justify-center gap-2 rounded-md border border-input bg-background px-4 py-2 text-sm font-medium hover:bg-accent hover:text-accent-foreground"
          >
            View on GitHub
          </a>
        </div>
      </header>

      <section className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
        <Card>
          <CardHeader>
            <FileText className="h-5 w-5 text-primary" />
            <CardTitle>Ingest</CardTitle>
            <CardDescription>
              Upload PDFs, Word docs, or plain text. We chunk, embed and index in the background.
            </CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            Hangfire jobs handle extraction with PdfPig and OpenXml; embeddings are generated by
            Azure OpenAI and stored in Azure AI Search.
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <MessageSquare className="h-5 w-5 text-primary" />
            <CardTitle>Ask</CardTitle>
            <CardDescription>
              Hybrid retrieval (vector + BM25) finds the right context. Streaming answers via SSE.
            </CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            Per-user index filters keep your data isolated. Citations link straight to the source
            page in a side preview.
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <Activity className="h-5 w-5 text-primary" />
            <CardTitle>Observe</CardTitle>
            <CardDescription>
              Production-ready: Serilog, Application Insights, health checks, rate limiting.
            </CardDescription>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            All deployed via Bicep + GitHub Actions to Azure App Service and Static Web Apps.
          </CardContent>
        </Card>
      </section>
    </div>
  )
}
